branches:
  except:
  - travis

environment:
  matrix:
  - PYTHON: Python35
  - PYTHON: Python36

install:
- SET PATH=C:\\%PYTHON%;%PATH%
- python --version
- python -m pip install aiohttp

build: off

test_script:
- python urlycue doc/README

# vim:ts=2 sts=2 sw=2 et
