dist: trusty
sudo: false
language: python
python:
- "3.5"
- "3.6"
- "3.7-dev"
matrix:
  allow_failures:
  - python: "3.7-dev"
install:
- pip install aiohttp
- pip install pydiatra
- pip install pyflakes
- pip install pylint
- pip install docutils pygments
script:
- private/run-pydiatra
- private/run-pyflakes
- if [[ ! "$TRAVIS_PYTHON_VERSION" =~ dev ]]; then private/run-pylint; fi
- private/check-rst
- make -C doc
- ./urlycue doc/README
- ./urlycue test/urls
- make install PREFIX=~/.local
- export PATH=~/.local/bin:"$PATH"
- urlycue --version
- export MANPATH=~/.local/share/man MANWIDTH=80
- man 1 urlycue | grep -A 10 -w URLYCUE

# vim:ts=2 sts=2 sw=2 et
