language: python
python:
- "3.5"
- nightly
cache:
  directories:
  - $HOME/.cache/pip
install:
- pip install aiohttp werkzeug
- pip install pyflakes
- pip install pylint
script:
- private/run-pyflakes
- private/run-pylint

# vim:ts=2 sts=2 sw=2 et
