dist: trusty
sudo: false
language: python
python:
- "3.5"
- "3.6"
- "3.7-dev"
install:
- pip install aiohttp
- pip install pydiatra
- pip install pyflakes
- pip install pylint
- pip install docutils pygments
script:
- private/run-pydiatra
- private/run-pyflakes
- if [[ ! "$TRAVIS_PYTHON_VERSION" =~ dev ]]; then private/run-pylint; fi
- private/check-rst
- make -C doc
- ./urlycue doc/README || [ $? -eq 2 ]
- ./urlycue test/urls || [ $? -eq 2 ]

# vim:ts=2 sts=2 sw=2 et
