dist: trusty
language: python
jobs:
  include:
  - python: "3.5"
    env: AIOHTTP=0.22.0
  - python: "3.6"
  - python: "3.7"
    dist: xenial
  - python: "3.8-dev"
    dist: xenial
branches:
  except:
  - appveyor
before_install:
- aiohttp=aiohttp${AIOHTTP+==$AIOHTTP}
- if [[ $TRAVIS_PYTHON_VERSION = *-dev ]]; then if_pylint=:; fi
install:
- python3 -m pip install $aiohttp
- python3 -m pip install pydiatra pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = *-dev ]]; then
    printf '\n\n    CONSTANT = ignore\n' >> $VIRTUAL_ENV/lib/python*/site-packages/pyflakes/checker.py;
  fi
- $if_pylint python3 -m pip install pylint
- python3 -m pip install docutils pygments
script:
- dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
- python3 -m pydiatra .
- python3 -m pyflakes .
- $if_pylint private/run-pylint
- private/check-rst
- make -C doc
- ./urlycue doc/README
- ./urlycue test/urls
- make install PREFIX=~/.local
- cd /
- urlycue --version
- export MANPATH=~/.local/share/man MANWIDTH=80
- man 1 urlycue | grep -A 10 -w URLYCUE

# vim:ts=2 sts=2 sw=2 et
