dist: trusty
sudo: false
language: python
matrix:
  include:
  - python: "3.5"
  - python: "3.6"
  - python: "3.7-dev"
    dist: xenial
    sudo: true
branches:
  except:
  - appveyor
before_install:
- if [[ $TRAVIS_PYTHON_VERSION = *-dev ]]; then if_pylint=:; fi
install:
- pip install aiohttp
- pip install pydiatra pyflakes
- $if_pylint pip install pylint
- pip install docutils pygments
script:
- dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
- python3 -m pydiatra .
- python3 -m pyflakes .
- $if_pylint private/run-pylint
- private/check-rst
- make -C doc
- ./urlycue doc/README
- ./urlycue test/urls
- make install PREFIX=~/.local
- cd /
- urlycue --version
- export MANPATH=~/.local/share/man MANWIDTH=80
- man 1 urlycue | grep -A 10 -w URLYCUE

# vim:ts=2 sts=2 sw=2 et
