language: python
python:
- "3.5"
- "3.6"
- "3.7-dev"
install:
- pip install aiohttp
- pip install pyflakes
- pip install pylint
- pip install docutils
script:
- private/run-pyflakes
- if [[ ! "$TRAVIS_PYTHON_VERSION" =~ dev ]]; then private/run-pylint; fi
- private/check-rst
- make -C doc

# vim:ts=2 sts=2 sw=2 et
