language: python
python:
- "3.5"
- "3.6-dev"
- "3.7-dev"
cache:
  directories:
  - $HOME/.cache/pip
install:
- pip install aiohttp
- pip install pyflakes
- pip install pylint
- pip install docutils
script:
- private/run-pyflakes
- private/run-pylint
- private/check-rst
- make -C doc

# vim:ts=2 sts=2 sw=2 et
