#!/usr/bin/env python3
# encoding=UTF-8

# Copyright © 2016-2023 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

'''
urlycue: a URL checker
'''

import sys

# ----------------------------------------

def error(message):
    try:
        import argparse  # pylint: disable=import-outside-toplevel
        ap = argparse.ArgumentParser()
        prog = ap.prog
    except ImportError:
        import optparse  # pylint: disable=deprecated-module,import-outside-toplevel
        ap = optparse.OptionParser()
        prog = ap.get_prog_name()
    message = str.join('', (prog, ': error: ', message, '\n'))
    ap.exit(1, message)

def require_python(*version):
    if sys.version_info < version:
        version_str = str.join('.', map(str, version))
        message = 'Python >= %s is required' % version_str
        error(message)

require_python(3, 6)

# ----------------------------------------

basedir = None
if basedir is not None:
    sys.path[:0] = [basedir]

import lib.cli  # pylint: disable=wrong-import-position

if __name__ == '__main__':
    lib.cli.main()

# vim:ts=4 sts=4 sw=4 et
