#!/bin/sh

# Copyright © 2014-2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u
cd "${0%/*}/.."
if [ $# -ge 2 ]
then
    printf '%s [commit]\n' "$0" >&2
    exit 1
fi
if ! [ -d .git ]
then
    printf '%s requires git checkout\n' "$0" >&2
    exit 1
fi
pwd="$PWD"
commit=${1:-HEAD}
commit=$(git describe --always "$commit")
name=$(git cat-file blob "$commit:doc/changelog" | head -n1 | cut -d ' ' -f 1)
date=$(git rev-list -1 --format=%cI "$commit" | grep -o '^....-..-..' | tr -d -)
version=$(git cat-file blob "$commit:doc/changelog" | head -n1 | cut -d ' ' -f2 | tr -d '()')
released=$(git cat-file blob "$commit:doc/changelog" | head -n1 | grep -v -w UNRELEASED || true)
[ -n "$released" ] || version="${version}rc${date}"
printf 'Commit: %s\nVersion: %s\n' "$commit" "$version" >&2
set -x
sourceroot=$(mktemp -d -t "$name-source-XXXXXX")
export TAR_OPTIONS='--owner root --group root --mode a+rX --format ustar --sort name'
export GZIP='-9 -n'
git archive "$commit" --prefix="$name-$version/" | tar -C "$sourceroot" -xf -
cd "$sourceroot"/*
rm .git*
rm .travis.yml
rm README.rst  # shipped as doc/README
mv LICENSE doc/
rm private/build-source-tarball
make -C doc/
cd ..
mkdir -p "$pwd/dist"
tar -czf "$pwd/dist/$name-$version.tar.gz" */
rm -r "$sourceroot"
set +x
cd "$pwd"
ls -d "dist/$name-$version.tar.gz"

# vim:ts=4 sts=4 sw=4 et
