#!/bin/sh

# Copyright © 2016-2017 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

here=${0%/*}
here=${here#./}
root="$here/../"
root=${root#private/../}
[ -n "$root" ] || root=.
rst2xml=$(command -v rst2xml) \
|| rst2xml=$(command -v rst2xml.py) \
|| { printf 'rst2xml not found\n' >&2; exit 1; }
options='--input-encoding=UTF-8 --output-encoding=UTF-8 --strict'
if [ $# -eq 0 ]
then
    find "$root" -name '*.rst'
    grep -rwl 'ft[=]rst' "$root"
else
    printf '%s\n' "$@"
fi |
xargs -L1 -t -I{} "$rst2xml" $options {} /dev/null

# vim:ts=4 sts=4 sw=4 et
