#!/bin/sh

# Copyright © 2016 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

PYTHON=${PYTHON:-python3}
if [ $# -eq 0 ]
then
    set -- \
        $(grep -l -r '^#!.*python' .) \
        $(find . -name '*.py')
fi
exec "$PYTHON" -m pyflakes "$@"

# vim:ts=4 sts=4 sw=4 et
