#!/bin/sh

# Copyright © 2015-2017 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

PYTHON=${PYTHON:-python3}
"$PYTHON" -m pylint --version >/dev/null || exit 1
if [ $# -eq 0 ]
then
    pyscripts=$(grep -l -r '^#!.*python' .)
    set -- lib $pyscripts
fi
log=$(mktemp -t pylint.XXXXXX)
"$PYTHON" -m pylint "$@" > "$log" || [ $? != 1 ]
! grep '^\w:' "$log" \
| grep '^\w:' \
| grep -v -P '^\w: (?!lib/).*: missing-docstring ' \
| grep '.' || exit 1
rm "$log"

# vim:ts=4 sts=4 sw=4 et
