name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        include:
        - python: '3.6'
          os: ubuntu-18.04
          aiohttp: aiohttp==0.22.1
        - python: '3.7'
          os: ubuntu-20.04
        - python: '3.8'
          os: ubuntu-20.04
        - python: '3.9'
          os: ubuntu-20.04
        - python: '3.10'
          os: ubuntu-20.04
        - python: '3.11-dev'
          os: ubuntu-20.04
          broken: broken
          # https://github.com/aio-libs/aiohttp/issues/6600 "aiohttp/_websocket.c:198:12: fatal error: longintrepr.h: No such file or directory"
          # https://github.com/aio-libs/frozenlist/issues/305 "frozenlist/_frozenlist.c:432:62: error: dereferencing pointer to incomplete type ‘PyFrameObject’ {aka ‘struct _frame’}"
          # https://github.com/aio-libs/yarl/issues/706 "yarl/_quoting_c.c:198:12: fatal error: longintrepr.h: No such file or directory"
    runs-on: ${{matrix.os}}
    continue-on-error: ${{(matrix.broken && true) || false}}
    steps:
    - uses: actions/checkout@v2
    - name: set up Python ${{matrix.python}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python}}
    - name: run pydiatra
      run: |
        python3 -m pip install pydiatra
        python3 -m pydiatra -v .
    - name: run pyflakes
      run: |
        python3 -m pip install pyflakes
        python3 -m pyflakes .
    - name: install aiohttp
      run: |
        python3 -m pip install ${{matrix.aiohttp || 'aiohttp'}}
    - name: run pylint
      run: |
        python3 -m pip install pylint
        private/run-pylint
    - name: check changelog
      run: |
        dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
    - name: check reST syntax
      run: |
        python3 -m pip install docutils pygments
        private/check-rst
    - name: build the man page
      run: |
        make -C doc
    - name: run tests
      run: |
        make test network=1
    - name: install
      run: |
        make install PREFIX=~/.local
    - name: check whether the executable was installed correctly
      run: |
        cd /
        urlycue --version
        urlycue --help
    - name: check whether the man page was installed correctly
      env:
        MANPATH: /home/runner/.local/share/man
        MANWIDTH: 80
      run: |
        cd /
        man 1 urlycue | grep -A 10 -w URLYCUE
  windows:
    strategy:
      matrix:
        include:
        - python: '3.6'
          os: windows-2019
          aiohttp: aiohttp==0.22.1
        - python: '3.10'
          os: windows-2019
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - name: set up Python ${{matrix.python}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python}}
    - name: install aiohttp
      run: |
        python3 -m pip install ${{matrix.aiohttp || 'aiohttp'}}
    - name: smoke test
      run: |
        python3 urlycue doc/README

# vim:ts=2 sts=2 sw=2 et
